<?php
/** @var \HK2\ScrollTop\Helper\Data $helper */
$helper = $this->helper('HK2\ScrollTop\Helper\Data');
?>
<?php if ($helper->isEnabled()): ?>
    <script type="text/javascript">
        require(['jquery'], function ($) {
            window.addEventListener('DOMContentLoaded', function() {
                var scrollOffset = <?= $helper->getScrollOffset() ?>;
                var scrollSpeed = <?= $helper->getScrollSpeed() ?>;
                var position = '<?= $helper->getButtonPosition() ?>';
                
                // Apply position classes
                $('#scrollTop_HK2').addClass('hk2-scrolltop-' + position);
                
                window.onscroll = function () {
                    if (document.body.scrollTop > scrollOffset || document.documentElement.scrollTop > scrollOffset) {
                        $('#scrollTop_HK2').fadeIn();
                    } else {
                        $('#scrollTop_HK2').fadeOut();
                    }
                };

                $('#scrollTop_HK2').click(function () {
                    $('html, body').animate({ scrollTop: 0 }, scrollSpeed);
                    return false;
                });
            });
        });
    </script>
<?php endif; ?>